### ISSUE TITLE
Client send a unknowed header.

### ISSUE THREAD

**Issue by pompierecattivo** [GHenkje/EasyTcp#5]
Hi All,
sorry for my bad english, at first..

I'm tryng to use Henkje library on a vb.net project (library was downloaed by nuget, version is 2.04) but i have a strange result.
Try to explain:
i've defined and start the connection, but all data i send to server, when received have a 1 chr prefix... in example: if i send
$OKMAP-V02;T;GM8-FAKEAGM_8;9.96574;45.01765;664;05/11/2019 12:03:02;19;134;0;3
the server receive
O$OKMAP-V02;T;GM8-FAKEAGM_8;9.96574;45.01765;664;05/11/2019 12:03:02;19;134;0;3;
or
P$OKMAP-V02;T;GM8-FAKEAGM_8;9.96574;45.01765;664;05/11/2019 12:03:02;19;134;0;3;
or some other chr prefix on string..

Note: I've used different TCP socket servers, but always i have same result...

Hope my explain is understandeable...

I dont attach the code because is very simple... just you have to know i hav to connect and close connection on each data transmit.

Any answer is appreciate.
Thanks.

**Comment by GHenkje** [comment]
Hello pompierecattivo,

The unknowed header is a byte[] of 2 bytes.
It contains the length of the message as an ushort and is used to prevent the messages from sticking together. If you dont use this you can remove the first 2 bytes of the message. I will create an update soon (1 or 2 weeks) so it can be disabled and the library can be used with other code.

**Comment by pompierecattivo** [comment]
Perfect! I understand the explanations. Thank you for your availability, I will wait for the changes. Your library seems one of the most simple and effective.

**Comment by GHenkje** [comment]
I did take a look at adding this option but this will be very hard. Can i ask you what you are using now? Did you create your own tcp server?
You can add the header by yourself if you want to send to the client and if you want to send to your server use this:
```cs
//Send data to server without header. Equal to client.Send(byte[] data);
client.Socket.Send(data);
```

Here i have an example of adding/removing the header with c#
It is using another library as server/client.
https://hastebin.com/amobavizud.cs

**Comment by pompierecattivo** [comment]
Hi Henkje,
thanks for answer.
I haven't an own server. i'm trying to send data to a tcp socket server
build-in in a GIS software. they need  to open and close connection each
data is trasmitted...
I will try your suggestion.
I'll let you know.


Maurizio CARLETTI
Via Sebastiano Ferrero, 5 - 13900 - Biella (BI) - Italia
Cell. 3498740950 - 3315771228 -  Fax 17802209715
COD.FIS. CRLMRZ69A09D205I
E-mail:
pompiere.cattivo@gmail.com
maurizio.carletti@vigilfuoco.it



Il giorno ven 17 mag 2019 alle ore 13:51 Henkje <notifications@github.com>
ha scritto:

**Comment by GHenkje** [comment]
Hello,
I found an very old version of EasyTcp the performance isn't perfect (~10 ms ping) But it isn't that bad compared with some other library's (It is async, but instead of async sockets it is using the new async tcpClient). This package won't add the header. Maybe this helps you.

Here the download:
(Tools > NuGet Package Manager > Package Manager Console)
Install-Package HenkTcp -Version 1.0.1 

[Also an zip file with the .nupkg file](https://github.com/GHenkje/EasyTcp/files/3196637/HenkTcp.zip)
